### PR TITLE
Rest joystick option

### PR DESCRIPTION
**Pull request by UniquePassive**

### CODE REVIEW

**Comment by yoannmoinet** [comment]
Very good ! Thanks for that !

Can you run the [build and bump the version](https://github.com/yoannmoinet/nipplejs#build) as well please?

**Comment by UniquePassive** [comment]
There we go. 😃

**Comment by yoannmoinet** [comment]
Thank you, I'll test it later today, and I'll merge it !

**Comment by yoannmoinet** [comment]
I've merged your two first commits, I'm prepping another version !
Thank you so much for your help!

**Pull request closed without merging**
