### PR TITLE
Fix stuck joystick issues (#31 and #33)

### PR DESCRIPTION
**Pull request by Kalkut**
Fixes https://github.com/yoannmoinet/nipplejs/issues/31 and https://github.com/yoannmoinet/nipplejs/issues/31

### CODE REVIEW

**Comment by yoannmoinet** [comment]
@Kalkut Thank you for this.
I'll have a look and test it.

What are the steps to reproduce the bug so I can test that your fix really works?

**Comment by Kalkut** [comment]
Actually after further testing, I still have to investigate.

I noticed this issue when I had two touchevents (one on the joystick and one on an unrelated canvas with touch capabilities). When I moved the joystick while also playing with the canvas and then released the joystick I saw it getting stuck.

I applied this fix : https://github.com/yoannmoinet/nipplejs/issues/31#issuecomment-283995243

At first it seemed fixed, but it still happens (way less often though). I now think that this fix is not enough yet

**Comment by yoannmoinet** [comment]
@Kalkut have you tried the solution given here #61 ?

**Comment by yoannmoinet** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
