### PR TITLE
Add support for overwriting the buildEl function

### PR DESCRIPTION
**Pull request by vladfr**
I needed to customize the HTML of the nipple elements, so I'm adding support to overwrite the `buildEl` function. Any suggestions on how this could be improved are welcome.

### CODE REVIEW

**Comment by yoannmoinet** [comment]
If you could add some documentation on how to use this, it would be 👌

**Comment by vladfr** [comment]
Hey @yoannmoinet, thanks! Added more checks, and added it in the Readme. I can't get all tests to pass, but most fail on the current master as well. I'll try to add a test for a simple `className` added via `buildEl`, and maybe I'll have time for an example as well.

One idea I had was to change this into a hook function? Instead of overwriting the whole `buildEl()`, I could add another function that gets called right after it?

``` 
// nipple.js:43
    this.buildEl()
        .stylize();

// would become:
    
    this.buildEl();
    if (this.options.dataOnly === false) {
          this.collection.afterBuildEl();
    }
    this.stylize();
```
WDYT?

**Comment by yoannmoinet** [comment]
Sorry for the delay @vladfr (started a new job in January).
I'll have a better look at this because this is a great idea, but I'm not sure about the implementation.
I feel like it's a bit complicated for a dev to implement a full function just to have his own element.

I'll figure something out.

**Comment by vladfr** [comment]
Hi,

Yes I hear you. That's why I didn't really push for it... It did the trick
as a hack, but indeed it should be done more cleanly.

**Pull request closed without merging**
